apiVersion: v1
kind: Service
metadata:
  name: todotask-service
spec:
  selector:
    app: todotask  # Replace my-app with todotask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
